### ISSUE TITLE
Update Insert Sampling Features Worksheet

### ISSUE THREAD

**Issue by FloodHydrology** [palmerlab-umd/choptank-db#2]
1)  Add “vegetables” disclaimer [e.g., this is just a tutorial, make your own damn script]
2)  Update to include “Related Features” table
3)  Define vocabulary for “related features” table

**Comment by khondula** [comment]
Related features table instructions updated here: https://palmerlab-umd.github.io/choptank-db/relate-samplingfeatures.html, including a link to the relationship type CV (http://vocabulary.odm2.org/relationshiptype/). 

I'm not sure there is an adequate relationship type for describing wells being "downstream" of wetland sites. Could use "isRelatedTo", come up with a new term, or not have it be a formal relationship and just have information in the site's description. in the sampling table.

**Comment by FloodHydrology** [comment]
I played with that some yesterday.  Maybe we can hold off on this for a little bit [e.g., network structure], and revisit once we finalize delineations.  This would be a good parallel effort with modeling work.

**Comment by khondula** [comment]
Okay sounds good. The related features table I would think of more for keeping track of which samples were collected at which site, and point locations within the wetland sites. More interpreted ‘real world’ things like where water flows can be outside of the database or revisited later, and for now maybe just embedded in some good “samplingfeaturedescription” entries.

--
Kelly L. Hondula
Quantitative Researcher and Computer Programmer
National Socio-Environmental Synthesis Center
University of Maryland
www.sesync.org
